name: "Bug Report"
description: "Submit a bug report to help us improve"
title: "[BUG] "
labels: bug,untriaged
body:
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: "Additional context to reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: "1.[...] 2.[...]"
  - type: textarea
    id: screenshots
    validations:
      required: false
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
     label: "Are you sure this issue hasn't been raised already?"
     options:
        - label: "Yes"
          required: true
